name: Create_Release

on:
# Runs on tagged commit
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
