# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build-Application

# Define events
on:
#   workflow_dispatch: <---Set for manual deployments
  # push event
  push:
    branches: [ "master" ]
  # pr event  
  pull_request:
    branches: [ "master" ]

# set of actions to execute
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: echo "Checking out repository..."
    # Checkout repo
    - uses: actions/checkout@v3
    # use specified node version from above matrix to install dependencies and run build script
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "Getting ready to install dependencies..."    
    - run: npm ci
    - run: echo "Dependencies installed."
    - run: echo "Initializing build..."
    - run: npm run build
    - run: echo "Build ran."